version: '3'
services:
  prom:
    ports:
      - "127.0.0.1:${PROMPORT}:${PROMPORT}"
    volumes:
      - "${PWD}/prometheus.yml:/etc/prometheus/prometheus.yml"
    image: prom/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
  grafana:
    links:
      - "prom:${PROMSERVICE}"
    image: grafana/grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - PROMSERVICE=${PROMSERVICE}
      - PROMPORT=${PROMPORT}
    volumes:
      - "${PWD}/grafana_datasource.yaml:/etc/grafana/provisioning/datasources/grafana_datasource.yaml"
      - "${PWD}/grafana_dashboard.yaml:/etc/grafana/provisioning/dashboards/grafana_dashboard.yaml"
      - "${PWD}/grafana_dashboard.json:/etc/dashboards/grafana_dashboard.json"
    ports:
      - "127.0.0.1:${GRAFANAPORT}:${GRAFANAPORT}"
  memcachemon:
    links:
      - "memcached:${MEMCACHEDSERVICE}"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:${METRICSPORT}:${METRICSPORT}"
    command:
      - -v
    environment:
      - MEMCACHEADDRESS=${MEMCACHEDSERVICE}
      - MEMCACHEPORT=${MEMCACHEPORT}
      - SLEEP=${SLEEP}
      - METRICSPORT=${METRICSPORT}
  memcached:
    image: memcached
    ports:
      - "127.0.0.1:${MEMCACHEPORT}:${MEMCACHEPORT}"
    command:
      - -vv
