{
 "title": "Memcachemon",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "memcache",
    "query": "label_values(memcachemon_request_duration_seconds_bucket, memcache)"
   }
  ]
 },
 "panels": [
  {
   "title": "Get Requests",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(memcachemon_request_duration_seconds_bucket{operation=\"get\", memcache=\"$memcache\"}[$__interval])) by (le))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Set Requests",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(memcachemon_request_duration_seconds_bucket{operation=\"set\", memcache=\"$memcache\"}[$__interval])) by (le))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Get Request Failures",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(memcachemon_request_failures_total{operation=\"get\", memcache=\"$memcache\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Set Request Failures",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(memcachemon_request_failures_total{operation=\"set\", memcache=\"$memcache\"}[$__interval]))"
    }
   ]
  }
 ]
}